/*
 * This source file was generated by the Gradle 'init' task
 */
package io.conduktor.demos.kafka;

public class ProducerDemo {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ProducerDemo().getGreeting());
    }
}
